/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloworld.java;

public class App {
    public String getGreeting() {
        return "Hello SonarCloud!!!";
    }
    
    public String getGoodbye() {
        return "Goodbye World!";
    }
    
    public String getGoodbye2() {
        return "Goodbye World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
